### PR TITLE
tidy messy zen-garden html

### PR DESCRIPTION
**Pull request by Joan-SHI**

### CODE REVIEW

**Comment by catherineedwards** [comment]
Hi Joan, some ideas for your code (as part of the role play exercise):
* On line 23, your code could read like this: `<h2>The Beauty of <abbr title="Cascading Style Sheets">CSS</abbr> Design</h2>`. This makes it look tidier.
* On line 36, the content following the `<p>` tag should be separated and then indented.

Otherwise, it looks good to me! Let me know when you've made the changes so I can update my progress, too! Cheers!

**Comment by Joan-SHI** [comment]
Hi Catherine, just saw your comment( I didn't realize that we need to check our git hub domains regularly ). Will check it tonight and give you feedback. :)

**Comment by catherineedwards** [comment]
Hi @Joan-SHI - no worries at all, I managed to complete the exercise with someone else so don't worry about it :) Cheers!

**Comment by catherineedwards** [comment]
Sweet, all done! Thanks @Joan-SHI !

**Pull request merged**
